version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-not-for-production
      - PORT=5000
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: python app.py
    restart: unless-stopped
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge