services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-me}
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge